"""Mode 1 command line: generate, review, and approve State Packs.

    python -m backend.statepack.cli generate M01            # LLM (needs Anthropic credentials)
    python -m backend.statepack.cli generate --all --offline # template generator, no network
    python -m backend.statepack.cli review M01
    python -m backend.statepack.cli approve M01 --by "Shift Lead"
    python -m backend.statepack.cli list
"""

from __future__ import annotations

import argparse
import sys

from .generator import LLMGenerator, TemplateGenerator, build_draft
from .profiles import DEFAULT_PATH, load_profiles
from .schema import SignalRule, StatePack
from .store import StatePackError, StatePackStore
from .validator import ValidationReport, validate


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="statepack", description=__doc__.splitlines()[0])
    parser.add_argument("--profiles", default=str(DEFAULT_PATH))
    parser.add_argument("--store", default="statepacks")
    sub = parser.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("generate", help="Generate draft State Packs")
    g.add_argument("machines", nargs="*")
    g.add_argument("--all", action="store_true")
    g.add_argument("--offline", action="store_true", help="Use the template generator instead of the LLM")

    r = sub.add_parser("review", help="Show a draft and its validation report")
    r.add_argument("machine")
    r.add_argument("--version", type=int)

    a = sub.add_parser("approve", help="Approve and freeze a draft")
    a.add_argument("machine")
    a.add_argument("--by", required=True, help="Name of the approving engineer")
    a.add_argument("--version", type=int)

    sub.add_parser("list", help="List stored packs")

    args = parser.parse_args(argv)
    profiles = load_profiles(args.profiles)
    store = StatePackStore(args.store)

    try:
        if args.cmd == "generate":
            ids = list(profiles) if args.all else args.machines
            if not ids:
                parser.error("name at least one machine, or pass --all")
            generator = TemplateGenerator() if args.offline else LLMGenerator()
            for mid in ids:
                profile = _profile(profiles, mid)
                pack, report = build_draft(profile, generator, store.next_version(mid))
                path = store.save_draft(pack)
                status = "OK" if report.ok else f"{len(report.errors)} error(s)"
                print(f"{mid}: v{pack.version} draft, {len(pack.states)} states, {status} → {path}")

        elif args.cmd == "review":
            profile = _profile(profiles, args.machine)
            pack = store.load_draft(args.machine, args.version)
            _print_pack(pack)
            _print_report(validate(pack.states, profile))

        elif args.cmd == "approve":
            profile = _profile(profiles, args.machine)
            path = store.approve(args.machine, profile, args.by, args.version)
            print(f"Approved and frozen → {path}")

        elif args.cmd == "list":
            for mid, version, status in store.list():
                print(f"{mid:6} v{version:<3} {status}")

    except StatePackError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    return 0


def _profile(profiles, machine_id):
    if machine_id not in profiles:
        raise StatePackError(f"Unknown machine {machine_id}. Known: {', '.join(profiles)}")
    return profiles[machine_id]


def _fmt_rule(r: SignalRule) -> str:
    lo = "-∞" if r.min is None else f"{r.min:g}"
    hi = "∞" if r.max is None else f"{r.max:g}"
    trend = "" if r.trend == "any" else f" ({r.trend})"
    return f"{r.signal.value} ∈ [{lo}, {hi}]{trend}"


def _print_pack(pack: StatePack) -> None:
    print(f"\n{pack.machine_id}  v{pack.version}  [{pack.status}]  generated by {pack.generated_by}\n")
    for s in pack.states:
        print(f"● {s.name}  —  {s.condition.value} → {s.action.value}, {s.urgency.value}")
        print(f"  {s.description}")
        for rule in s.signature:
            print(f"    · {_fmt_rule(rule)}")
        if s.likely_causes:
            print(f"  causes: {', '.join(s.likely_causes)}")
        print(f"  operator: {s.operator_guidance}\n")


def _print_report(report: ValidationReport) -> None:
    print("Validation:", "PASS" if report.ok else "FAIL")
    for e in report.errors:
        print(f"  ✗ {e}")
    for w in report.warnings:
        print(f"  ! {w}")


if __name__ == "__main__":
    sys.exit(main())
